server {
    listen 80;
    server_name www.vulkanspielepoland.pl;
    return 301 https://vulkanspielepoland.pl$request_uri;
}

server {
    listen 80 default_server;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ $uri/index.html =404;
    }

    error_page 404 /404.html;
}
